### ISSUE TITLE
Introduction Screen

### ISSUE THREAD

**Issue by standup2go** [LazzyBee/LazyBee-iOS#36]
Define Intro slide that displays for the first time app runs

**Comment by standup2go** [comment]
Draft ở đây
https://wireframepro.mockflow.com/view/lazzybee-intro

**Comment by standup2go** [comment]
Slides:
`1. LazzyBee là ứng dụng học từ vựng nghiêm túc, dành cho những người có mục tiêu rõ ràng. Bởi vậy bạn cần thật sự hiểu và làm theo đúng phương pháp.`
> Em sẽ đọc kỹ hướng dẫn sử dụng

`2. LazzyBee áp dụng các nghiên cứu khoa học trí nhớ, nên đảm bảo chắc chắn bạn sẽ nhớ được 2000 từ mỗi năm. Hãy bám sát mục tiêu này`
> Em hứa sẽ theo đuổi mục đích

`3. Được thiết kế tối ưu để học đều đặn hàng ngày, mỗi ngày khoảng 5 phút. Nếu bạn không thể sắp xếp được 5 phút, hẳn bạn có nhiều việc quan trong hơn để làm.`
> Em hứa sẽ học 5 phút mỗi ngày

`4. Để đạt được mục đích, bạn phải kiên trì theo đuổi. Không có ứng dụng nào có thể làm bạn say mê học ngoài sự quyết tâm.`
> Người thành công không bỏ cuộc

`5. Chúng tôi đề cao sự đơn giản và hiệu quả, nên việc học sẽ đơn điệu. Nếu bạn chỉ thích học theo hứng, e rằng đây không phải ứng dụng phù hợp`
> Mục tiêu giúp tôi có hứng thú

@HuKhong : Comment text của chú xem sao?

**Comment by HuKhong** [comment]
1. 5 phút tập trung và nghiêm túc mỗi ngày.
Bạn cần hiểu và làm đúng phương pháp.
 Check box: Đọc kỹ hướng dẫn. (check vào sẽ show hướng dẫn lên).

2. Mục tiêu tăng 2000 từ trong 1 năm.
Check box: Tôi quyết theo đuổi mục tiêu.

3. Duy trì STREAK với LazzyBee để đảm bảo hoàn thành mục tiêu.
Check box: Tôi hứa sẽ học 5p mỗi ngày.

4. Ứng dụng dành cho người kiên trì.
Check box: Người thành công không bỏ cuộc

5. Muốn hiệu quả mở Lazzy Bee. Muốn vui hãy mở game.
Check box: Tôi chọn Lazzy Bee ✌️ 

PHải check hết các box mới bắt đâu học.

**Comment by standup2go** [comment]
Trong thời gian nghĩ text, mình sẽ update sẵn sàng tính năng:
1. Màn hình đầu tiên là select Language: Anh vs Việt. Chọn ngôn ngữ nào thì sẽ ghi ngôn ngữ đó vào setting luôn (hiện nay đang mặc định là tiếng Việt)
2. Các slide giới thiệu:
Slide 1: LazzyBee sẽ giúp bạn học và nhớ được 2000 từ mới một năm ...
Slide 2: ... với điều kiện bạn phải học 5 phút mỗi ngày
Slide 3: Những từ bạn đã học sẽ không bị quên do được ôn lại đúng thời điểm
Slide 4: Trong khi học, hãy vuốt sang trái để xem từ điển
Slide 5: Bạn nên đọc kỹ hướng dẫn sử dụng để hiểu về cách học đặc biệt của chúng tôi.
Slide 6: Good luck!
3. Các slide có nút "Next", slide cuối cùng là nút "Start"

**Comment by standup2go** [comment]
English version
Slide 1: LazzyBee helps you learn and remember 2000 new words per year ...
Slide 2: ... if you spend 5 minutes each day
Slide 3: Words you learned will never be forgotten due to in-time-review
Slide 4: As you learn, swipe left to access embedded dictionary
Slide 5: You read guideline carefully to understand our special methodology
Slide 6: Good luck!

**Comment by standup2go** [comment]
Slide 2: ... if you JUST spend 5 minutes each day
Slide 2: ... chỉ cần bạn học 5 phút mỗi ngày

**Comment by HuKhong** [comment]
Done
