### ISSUE TITLE
Post learning screen

### ISSUE THREAD

**Issue by standup2go** [LazzyBee/LazyBee-iOS#37]
Với new users, những ngày học đầu tiên sẽ rất nhanh & khả năng cao là họ không hiểu cách học, nên tỷ lệ người quay trở lại rất ít. Cần có thêm các thông tin giới thiệu giúp người học hiểu rõ

**Comment by standup2go** [comment]
Sẽ có một bảng tổng kết sau khi học, đại loại:
Hôm nay:
Số từ ôn lại: 20
Số từ quên: 3
Số từ mới: 5
###########
Ngày mai:
Số từ ôn lại: 25
Số từ mới: 5
###########
Ứng dụng luôn ưu tiên ôn lại các từ sắp quên, để bạn luôn nhớ những gì đã học. Hãy kiên nhẫn!

**Comment by HuKhong** [comment]
Done
