### ISSUE TITLE
Help board

### ISSUE THREAD

**Issue by standup2go** [LazzyBee/LazyBee-iOS#38]
Bảng help hiện nay đang show userguide, mà thường thì user rất lười đọc.

Ta sẽ chuyển thành 1 bảng kiểu hỏi đáp hoặc listing các vấn đề quan trọng cùng đường link tới blog.

**Comment by HuKhong** [comment]
Thêm một mục ở Side Menu: Blog, bấm vào sẽ mở blog lazzy bee trên browser.

**Comment by standup2go** [comment]
Các thông tin bổ sung/Additional infomation

LazzyBee giúp bạn học 2000 từ/năm chỉ với 5 phút mỗi ngày
LazzyBee helps you learn 2000 words/year with only 5 minutes everyday
->http://www.lazzybee.com/blog/can_you_learn_2000_words_per_year

Các sai lầm thường gặp
Common mistakes
->http://www.lazzybee.com/blog/common_mistakes

Trí nhớ và hiệu ứng dãn thời gian
Memory and spacing effect
->http://www.lazzybee.com/blog/spacing_effect

Hướng dẫn sử dụng
Userguide
->http://www.lazzybee.com/blog/user_guide_2

Kiểm tra từ vựng
Vocabulary test
-> http://www.lazzybee.com/blog/how_accurate_the_test_is

Hỏi đáp về LazzyBee
LazzyBee Q&A
->http://www.lazzybee.com/blog/q&a

**Comment by HuKhong** [comment]
done
