### ISSUE TITLE
Support link

### ISSUE THREAD

**Issue by standup2go** [LazzyBee/LazyBee-iOS#39]
Thêm mục "Support/Hỗ trợ" vào menu, và xem các chỗ report lỗi hay gì đó sẽ đều hiển thị cái dialog hỗ trợ ra. Nội dung của dialog:
Chúng tôi sử dụng Discord để hỗ trợ các bạn, hãy sử dụng link sau để liên lạc với chúng tôi 24/24 https://discord.gg/ds3G6Ek

We provide support through Discord, click the following link to reach us 24/24 https://discord.gg/ds3G6Ek

**Comment by standup2go** [comment]
Thêm text sau dưới đường link, sau đó là nút copy để copy link:

Nếu bạn không muốn cài ứng dụng Discord, hãy copy và mở link trên desktop
"Copy"

**Comment by HuKhong** [comment]
Done
